### ISSUE TITLE
MelonLoader issue

### ISSUE THREAD

**Issue by JakeRuCodes** [Kalybr50/DevourClient#2]
Everything works on the v6.0 on MelonLoader but the new MelonLoader.dll doesn't work neither does the DevourClient provided in the newest release.

**Comment by Kalybr50** [comment]
With the latest update, the client switched to a new version of MelonLoader

**Comment by sanlimikasha** [comment]
> 在最新更新中，客户端切换到了新版本的 MelonLoader。在新的更新中一切正常。

I won't use Ask to share
